### ISSUE TITLE
Branch: Jim 0.3.0

### ISSUE THREAD

**Issue by topfunky** [quirkey/soca#15]
I needed the multi-bundle support in Jim 0.3.0. I implemented it in a branch here:

```
https://github.com/topfunky/soca/tree/feature/jim-030
```

I'm using it to build separate default and test bundles so I can write JavaScript tests with Jasmine (without triggering all the Ajax calls in the production app).

**Comment by quirkey** [comment]
Hey @topfunky

Sorry you had to duplicate work - already had this sitting in a local branch along with a release path for 0.2.0 (which I just pushed). Working on this a bunch over the next little while though. Very open to ideas as well.
Thanks! --AQ
