### ISSUE TITLE
building validations

### ISSUE THREAD

**Issue by bmidgley** [quirkey/soca#23]
Is there a way to populate validate_doc_update in the design document other than creating validate_doc_update.js in the root of the application? I'd like to compose the validations from several sources. What kind of approach for this would you accept if it requires patching?

**Comment by quirkey** [comment]
Like python couchapp you could use the Macro plugin to include helper methods from multiple sources. Another Idea could be a "validations" entry in the config.json that lists validations as seperate files in an ordered array:

``` js
{
  //...
  "validations": [
     "validations/user.js",
     "validations/mydoc.js",
   //...
  ]
}
```

I would definitely accept that as a pull request.

**Comment by bmidgley** [comment]
We ended up using couch's server-side js includes to pull validators for each kind of document together into the main validator. We're doing something similar for update handling and accessors (accessors are what we call the generic object get that is rewritten to go through our own kind of checker)
