### ISSUE TITLE
support for multiple databases?

### ISSUE THREAD

**Issue by bmidgley** [quirkey/soca#24]
I've seen a best-practices suggestion to put different document types in different databases even thought they are part of the same app. Is it possible for soca to work this way? It seems config.js does not allow it. It should probably contain an array of databases.

Even if we put almost everything in one database, there doesn't seem to be a way to do something like add a validation to the _users db design document. Is there a workaround or should I look at redesigning config.js and the main process flow?

**Comment by quirkey** [comment]
soca like other couchapp implementations really just manages a single design document which would live in a single DB. If you wanted to store your user created or other file documents in a different DB this would be determined in your Sammy app or JS and soca really isnt stopping you there.

It is true that soca doesnt handle/manipulate the _users DB right now and I could see that being a useful feature (though it only applies to latest couchdb) if someone wanted to pitch in and help with it.

**Comment by bmidgley** [comment]
We created a separate soca app for manipulating _users.

**Comment by quirkey** [comment]
Cool, good idea  - if there are some reusable bits in there it would be great to share

**Comment by steve-ross** [comment]
It would be nice if you could support multiple design docs then in a multi db (same application) scenario you could have a design doc that only includes the views that you need for that specific db and keep the html etc in the public db.
