### ISSUE TITLE
Confusing message when using compass plugin (soca-0.2.0)

### ISSUE THREAD

**Issue by mcmlxxxiii** [quirkey/soca#30]
**$ cat hooks/before_build.rb**
plugin 'compass'

**$ soca push**
Sass is in the process of being separated from Haml,
and will no longer be bundled at all in Haml 3.2.0.
Please install the 'sass' gem if you want to use Sass.

**Comment by quirkey** [comment]
This isnt an error but a warning from the compass/sass/haml gem set. It should be fixed upstream when compass is updated.

**Comment by mcmlxxxiii** [comment]
Yes, you're right. I've created an issue and soon realized that it is not worth all those letters. But you know, issue creator on Github cannot delete it.
