### ISSUE TITLE
soca push error -- undefined method 'plugin' for Soca::Pusher

### ISSUE THREAD

**Issue by jnisenson** [quirkey/soca#32]
I installed the soca gem, then did a soca generate, moved into the generated directory and tried a soca push......ran into the following:

prompt $ soca push
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:120:in `instance_eval': undefined method`plugin' for #Soca::Pusher:0x00000102341b58 (NoMethodError)
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:120:in `instance_eval'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:120:in`block in run_hook_file!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:119:in `chdir'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:119:in`run_hook_file!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:111:in `run_hooks!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:33:in`build'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/pusher.rb:83:in `push!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/lib/soca/cli.rb:111:in`push'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@global/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@global/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@global/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@global/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/soca-0.3.1/bin/soca:5:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/bin/soca:19:in`load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/bin/soca:19:in `<main>'

**Comment by quirkey** [comment]
Looks like the most recent version shipped with some bad templates - thanks for the catch, will fix.
