### ISSUE TITLE
Install fails with thor dependency problem

### ISSUE THREAD

**Issue by dwt** [quirkey/soca#34]
Installing soca on ubuntu I got an install error because jim depends on thor 0.14 and soca depends on thor 0.15.

**Comment by steam0r** [comment]
same here on ubuntu as well. is there any resolution to this?

**Comment by bleeppurple** [comment]
fails on osx lion ...

**Comment by biggihs** [comment]
Fails on Mint (maya) also.

**Comment by quirkey** [comment]
Sorry, somehow this slipt through notifications. Pushed an updated version with fixed dependencies to rubygems
